# Generated by Django 4.0 on 2022-02-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': [('can_mark_returned', 'Set book as returned'), ('can_mark_on_loan', 'Set book as on loan')]},
        ),
    ]
